services:
  # Development overrides
  postgres:
    environment:
      - POSTGRES_PASSWORD=dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - ./Backend/innkt.Officer/init-scripts:/docker-entrypoint-initdb.d:ro

  redis:
    command: redis-server --appendonly yes --requirepass dev_redis_123
    ports:
      - "6379:6379"

  kafka:
    ports:
      - "9092:9092"
      - "9101:9101"

  zookeeper:
    ports:
      - "2181:2181"

  officer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=innkt_db;Username=innkt_user;Password=dev_password_123
      - Redis__ConnectionString=redis:6379,password=dev_redis_123
      - Kafka__BootstrapServers=kafka:29092
    ports:
      - "5004:5004"
      - "5005:5005"
    volumes:
      - ./Backend/innkt.Officer:/app:ro
      - /app/bin
      - /app/obj

  neurospark:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379,password=dev_redis_123
      - Kafka__BootstrapServers=kafka:29092
      - Officer__BaseUrl=http://officer:5004
    ports:
      - "5006:5006"
      - "5007:5007"
    volumes:
      - ./Backend/innkt.NeuroSpark:/app:ro
      - /app/bin
      - /app/obj

  web-client:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5006
      - REACT_APP_OFFICER_URL=http://localhost:5004
      - REACT_APP_NEUROSPARK_URL=http://localhost:5006
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app:ro
      - /app/node_modules
    command: npm start

  # Development tools
  adminer:
    image: adminer:latest
    container_name: innkt-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - innkt-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: innkt-kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - innkt-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: innkt-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:dev_redis_123
    depends_on:
      - redis
    networks:
      - innkt-network


