services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: innkt-postgres
    environment:
      POSTGRES_DB: innkt_officer
      POSTGRES_USER: admin_officer
      POSTGRES_PASSWORD: "CAvp57rt26"
      POSTGRES_MULTIPLE_DATABASES: innkt_social,innkt_groups,innkt_follow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/innkt.Officer/init_complete.sql:/docker-entrypoint-initdb.d/01-init-complete.sql
    networks:
      - innkt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_officer -d innkt_officer"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: innkt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - innkt-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Database with Replica Set (required for Change Streams)
  mongodb:
    image: mongo:7
    container_name: innkt-mongodb
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: innkt_social
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongodb-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    networks:
      - innkt-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Replica Set Initialization
  mongodb-setup:
    image: mongo:7
    container_name: innkt-mongodb-setup
    depends_on:
      - mongodb
    command: >
      mongosh --host mongodb:27017 --eval "
      try {
        rs.status();
        print('Replica set already initialized');
      } catch (e) {
        print('Initializing replica set...');
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongodb:27017' }
          ]
        });
        print('Replica set initialized successfully');
      }
      "
    networks:
      - innkt-network
    restart: "no"

  # Kafka Message Broker
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: innkt-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - innkt-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: innkt-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - innkt-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka UI (for monitoring)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: innkt-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - innkt-network

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  kafka_data:

networks:
  innkt-network:
    driver: bridge
