version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: innkt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: innkt_officer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - innkt-network

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: innkt-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: innkt_content
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - innkt-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: innkt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - innkt-network

  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: innkt-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - innkt-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: innkt-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - innkt-network

  # Kafka UI (Optional - for development)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: innkt-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - innkt-network

  # MySQL Admin (Optional - for development)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: innkt-phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - innkt-network

  # MongoDB Express (Optional - for development)
  mongo-express:
    image: mongo-express:latest
    container_name: innkt-mongo-express
    depends_on:
      - mongodb
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    networks:
      - innkt-network

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
  kafka_data:

networks:
  innkt-network:
    driver: bridge





