apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: innkt
  labels:
    app: frontend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: innkt-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: innkt
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
