apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-minimal
  namespace: innkt
  labels:
    app: kafka-minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-minimal
  template:
    metadata:
      labels:
        app: kafka-minimal
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-minimal:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx256M -Xms128M"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-minimal-service
  namespace: innkt
  labels:
    app: kafka-minimal
spec:
  selector:
    app: kafka-minimal
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  type: ClusterIP