apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
  namespace: innkt
  labels:
    app: messaging-service
    service: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
        service: messaging
    spec:
      containers:
      - name: messaging-service
        image: innkt-messaging:latest
        imagePullPolicy: IfNotPresent  # Use local image if available
        ports:
        - containerPort: 5003
          name: http
        - containerPort: 3000
          name: websocket
        env:
        - name: NODE_ENV
          value: "development"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/innkt_messaging"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: innkt-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: innkt
  labels:
    app: messaging-service
spec:
  selector:
    app: messaging-service
  ports:
  - name: http
    port: 5003
    targetPort: 5003
    protocol: TCP
  - name: websocket
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
