apiVersion: apps/v1
kind: Deployment
metadata:
  name: neurospark-service
  namespace: innkt
  labels:
    app: neurospark-service
    service: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neurospark-service
  template:
    metadata:
      labels:
        app: neurospark-service
        service: ai
    spec:
      containers:
      - name: neurospark-service
        image: innkt-neurospark:latest
        imagePullPolicy: IfNotPresent  # Use local image if available
        ports:
        - containerPort: 5003
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: innkt-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://+:5003"
        - name: ASPNETCORE_Kestrel__Endpoints__Http__Url
          value: "http://+:5003"
        - name: ASPNETCORE_Kestrel__Endpoints__Https__Url
          value: ""
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "1"
        - name: Kafka__BootstrapServers
          valueFrom:
            configMapKeyRef:
              name: innkt-config
              key: KAFKA_BOOTSTRAP_SERVERS
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: neurospark-service
  namespace: innkt
  labels:
    app: neurospark-service
spec:
  selector:
    app: neurospark-service
  ports:
  - name: http
    port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP
