apiVersion: apps/v1
kind: Deployment
metadata:
  name: officer-service
  namespace: innkt
  labels:
    app: officer-service
    service: identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: officer-service
  template:
    metadata:
      labels:
        app: officer-service
        service: identity
    spec:
      containers:
      - name: officer-service
        image: innkt-officer:sha-b421d442
        imagePullPolicy: IfNotPresent  # Use local image if available
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: innkt-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: innkt-config
              key: ASPNETCORE_URLS
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-service;Port=5432;Database=innkt_officer;Username=admin_officer;Password=@CAvp57rt26;TrustServerCertificate=true;"
        - name: ConnectionStrings__Redis
          valueFrom:
            configMapKeyRef:
              name: innkt-config
              key: REDIS_CONNECTION_STRING
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: officer-service
  namespace: innkt
  labels:
    app: officer-service
spec:
  selector:
    app: officer-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
